### ISSUE TITLE
Discovery "Asking what people want"

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/Agile-Delivery-Process#4]
> path: (do not delete) https://github.com/bcgov/Agile-Delivery-Process/blob/master/02_Discovery.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Agile-Delivery-Process/Discovery

## Content Issue
I don't fully agree with this statement in the section "What do you do in Discovery"

"ask users what they **want** in a service"

## Rationale
In design research, it's found not to be a productive practice asking what people "want". We try to understand what people "need". 

Maybe this is just me interpreting this bullet as a direct translation of going to users and saying "what do you want?". While this might not be the case, I wouldn't want people to interpret it this way.

Would suggest changing it to say: 

"understand what users' need in a service"

**Comment by mark-a-wilson** [comment]
@dlevineBC - I agree.

**Comment by dlevineBC** [comment]
Change has been made!
